export const products = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas incidunt sint explicabo a et asperiores, voluptatibus, dolor suscipit similique nemo placeat aliquid quam. Molestias debitis, ipsa aperiam harum animi suscipit?',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas incidunt sint explicabo a et asperiores, voluptatibus, dolor suscipit similique nemo placeat aliquid quam. Molestias debitis, ipsa aperiam harum animi suscipit?',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.webp',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas incidunt sint explicabo a et asperiores, voluptatibus, dolor suscipit similique nemo placeat aliquid quam. Molestias debitis, ipsa aperiam harum animi suscipit?',
    brand: 'Cannon',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas incidunt sint explicabo a et asperiores, voluptatibus, dolor suscipit similique nemo placeat aliquid quam. Molestias debitis, ipsa aperiam harum animi suscipit?',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.webp',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas incidunt sint explicabo a et asperiores, voluptatibus, dolor suscipit similique nemo placeat aliquid quam. Molestias debitis, ipsa aperiam harum animi suscipit?',
    brand: 'Logitech',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas incidunt sint explicabo a et asperiores, voluptatibus, dolor suscipit similique nemo placeat aliquid quam. Molestias debitis, ipsa aperiam harum animi suscipit?',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 2.5,
    numReviews: 12,
  },
];
